"""create patients table

Revision ID: 0c19e08fea8f
Revises: 81b902ce564a
Create Date: 2026-08-07 20:47:06.681325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c19e08fea8f'
down_revision: Union[str, None] = '81b902ce564a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patients_id', table_name='patients')
    op.drop_index('ix_patients_patient_code', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('gender', mysql.ENUM('Male', 'Female', 'Other'), nullable=False),
    sa.Column('disease', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('admission_date', sa.DATE(), nullable=False),
    sa.Column('discharge_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name='patients_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_patients_patient_code', 'patients', ['patient_code'], unique=True)
    op.create_index('ix_patients_id', 'patients', ['id'], unique=False)
    # ### end Alembic commands ###
