"""add prescriptions table

Revision ID: 79202a8f73c9
Revises: c724d25dad99
Create Date: 2026-08-07 23:43:58.580370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79202a8f73c9'
down_revision: Union[str, None] = 'c724d25dad99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prescription_medicines_id', table_name='prescription_medicines')
    op.drop_table('prescription_medicines')
    op.add_column('prescriptions', sa.Column('medicines', sa.Text(), nullable=True))
    op.add_column('prescriptions', sa.Column('dosage_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'dosage_instructions')
    op.drop_column('prescriptions', 'medicines')
    op.create_table('prescription_medicines',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prescription_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('medicine_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('dosage', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('frequency', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('duration', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('route', mysql.ENUM('Oral', 'Topical', 'Intravenous', 'Intramuscular', 'Inhalation', 'Other'), nullable=False),
    sa.Column('is_antibiotic', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('antibiotic_class', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sensitivity_test', mysql.TEXT(), nullable=True),
    sa.Column('resistance_notes', mysql.TEXT(), nullable=True),
    sa.Column('instructions', mysql.TEXT(), nullable=False),
    sa.Column('timing', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('special_instructions', mysql.TEXT(), nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('refill_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_refills', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_taken', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('taken_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='prescription_medicines_ibfk_2'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name='prescription_medicines_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_prescription_medicines_id', 'prescription_medicines', ['id'], unique=False)
    # ### end Alembic commands ###
