"""Add prescriptions table

Revision ID: a75c15d3d0e0
Revises: ed51a269a9bf
Create Date: 2026-08-07 22:21:13.399624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75c15d3d0e0'
down_revision: Union[str, None] = 'ed51a269a9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescription_code', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('prescribed_medicines', sa.Text(), nullable=True),
    sa.Column('dosage_instructions', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('prescription_date', sa.Date(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('is_refillable', sa.Boolean(), nullable=True),
    sa.Column('refill_count', sa.Integer(), nullable=True),
    sa.Column('max_refills', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_index(op.f('ix_prescriptions_prescription_code'), 'prescriptions', ['prescription_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_prescription_code'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    # ### end Alembic commands ###
