"""Add appointments table

Revision ID: e6e2f80f5d52
Revises: 79202a8f73c9
Create Date: 2026-08-08 00:25:40.333557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6e2f80f5d52'
down_revision: Union[str, None] = '79202a8f73c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_appointment_code', table_name='appointments')
    op.drop_index('ix_appointments_id', table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('appointment_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('appointment_date', sa.DATE(), nullable=False),
    sa.Column('appointment_time', mysql.TIME(), nullable=False),
    sa.Column('reason', mysql.TEXT(), nullable=False),
    sa.Column('symptoms', mysql.TEXT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('follow_up_date', sa.DATE(), nullable=True),
    sa.Column('follow_up_notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name='appointments_ibfk_2'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='appointments_ibfk_1'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name='appointments_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_appointments_id', 'appointments', ['id'], unique=False)
    op.create_index('ix_appointments_appointment_code', 'appointments', ['appointment_code'], unique=True)
    # ### end Alembic commands ###
