"""Add prescriptions table

Revision ID: ed51a269a9bf
Revises: ca0bbaa371e3
Create Date: 2026-08-07 22:11:37.205125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed51a269a9bf'
down_revision: Union[str, None] = 'ca0bbaa371e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
